import type { TFunction } from "i18next";

export const getCommonSettingInputs = (t: TFunction) => [
  {
    type: "range",
    name: "fontSize",
    min: 10,
    max: 25,
    label: t("Auth.Settings.FontSize"),
    defaultValue: 15,
    fullWidth: true,
  },
  {
    type: "select",
    name: "theme",
    label: t("Auth.Settings.User.System.Theme"),
    options: [
      { label: t("Auth.Settings.User.System.LightMode"), value: "light" },
      { label: t("Auth.Settings.User.System.DarkMode"), value: "dark" },
    ],
    defaultValue: "light",
    fullWidth: true,
  },
  {
    type: "select",
    name: "layoutMode",
    label: t("Auth.Settings.User.System.LayoutMode"),
    options: [
      { label: t("Auth.Settings.User.System.HorizontalLayout"), value: "horizontal" },
      { label: t("Auth.Settings.User.System.VerticalLayout"), value: "vertical" },
    ],
    defaultValue: "horizontal",
    fullWidth: true,
  },
  {
    type: "select",
    name: "layoutWidth",
    label: t("Auth.Settings.User.System.LayoutWidth"),
    options: [
      { label: t("Auth.Settings.User.System.FullWidth"), value: "full-width" },
      { label: t("Auth.Settings.User.System.BoxedWidth"), value: "boxed" },
    ],
    defaultValue: "full-width",
    fullWidth: true,
  },
  {
    type: "color",
    name: "primaryColor",
    label: t("Auth.Settings.User.System.PrimaryColor"),
    defaultValue: "#1e4c9d",
    fullWidth: true,
  },
  {
    type: "color",
    name: "secondaryColor",
    label: t("Auth.Settings.User.System.SecondaryColor"),
    defaultValue: "#dfe5ea",
    fullWidth: true,
  },
  {
    type: "select",
    name: "timezone",
    label: t("Auth.Settings.User.System.Timezone"),
    options: [
      { label: "UTC", value: "UTC" },
      { label: "EST (UTC-5)", value: "EST" },
      { label: "CST (UTC-6)", value: "CST" },
      { label: "MST (UTC-7)", value: "MST" },
      { label: "PST (UTC-8)", value: "PST" },
      { label: "IST (UTC+5:30)", value: "IST" },
      { label: "GST (UTC+4)", value: "GST" },
      { label: "CET (UTC+1)", value: "CET" },
    ],
    defaultValue: "UTC",
    fullWidth: true,
  },
  {
    type: "select",
    name: "dateFormat",
    label: t("Auth.Settings.User.System.DateFormat"),
    options: [
      { label: "MM/DD/YYYY", value: "MM/DD/YYYY" },
      { label: "DD/MM/YYYY", value: "DD/MM/YYYY" },
      { label: "YYYY-MM-DD", value: "YYYY-MM-DD" },
      { label: "DD.MM.YYYY", value: "DD.MM.YYYY" },
    ],
    defaultValue: "MM/DD/YYYY",
    fullWidth: true,
  },
  {
    type: "select",
    name: "defaultLanguage",
    label: t("Auth.Settings.User.System.DefaultLanguage"),
    options: [
      { label: "English", value: "en" },
      { label: "العربية", value: "ar" },
    ],
    defaultValue: "en",
    fullWidth: true,
  },
];
