import type { TFunction } from "i18next";

export const inputs = (t: TFunction) => () => [
  {
    name: "identityLabel",
    label: t("Auth.Settings.Admin.Metadata.IdentityLabel"),
    type: "label",
  },
  {
    name: "name",
    label: t("Auth.Settings.Admin.Metadata.Name"),
    type: "text",
    required: true,
    double: true,
  },
  {
    name: "logo",
    label: t("Auth.Settings.Admin.Metadata.Logo"),
    type: "text",
    required: true,
    double: true,
  },
  {
    name: "logoFull",
    label: t("Auth.Settings.Admin.Metadata.FullLogo"),
    type: "text",
    required: true,
    double: true,
  },
  {
    name: "slogan",
    label: t("Auth.Settings.Admin.Metadata.Slogan"),
    type: "text",
    required: true,
    double: true,
  },
  {
    name: "defaultThemeColor",
    label: t("Auth.Settings.Admin.Metadata.ThemeColor"),
    type: "color",
    required: true,
    double: true,
  },
  {
    name: "contactsLabel",
    label: t("Auth.Settings.Admin.Metadata.ContactsLabel"),
    type: "label",
  },
  {
    name: "phoneNumber",
    label: t("Auth.Settings.Admin.Metadata.PhoneNumber"),
    type: "numberText",
    required: false,
    double: true,
  },
  {
    name: "websiteUrl",
    label: t("Auth.Settings.Admin.Metadata.WebsiteUrl", "Website URL"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "contactEmail",
    label: t("Auth.Settings.Admin.Metadata.ContactEmail", "Contact Email"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "socialFacebook",
    label: t("Auth.Settings.Admin.Metadata.SocialFacebook", "Facebook URL"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "socialInstagram",
    label: t("Auth.Settings.Admin.Metadata.SocialInstagram", "Instagram URL"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "socialLinkedin",
    label: t("Auth.Settings.Admin.Metadata.SocialLinkedin", "LinkedIn URL"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "socialTwitter",
    label: t("Auth.Settings.Admin.Metadata.SocialTwitter", "Twitter/X URL"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "socialYoutube",
    label: t("Auth.Settings.Admin.Metadata.SocialYoutube", "YouTube URL"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "socialTiktok",
    label: t("Auth.Settings.Admin.Metadata.SocialTiktok", "TikTok URL"),
    type: "text",
    required: false,
    double: true,
  },
  {
    name: "passwordPolicyLabel",
    label: t("Auth.Settings.Admin.Metadata.PasswordPolicyLabel"),
    type: "label",
  },
  {
    name: "passwordMinLength",
    label: "Password Min Length",
    type: "number",
    required: true,
    double: true,
  },
  {
    name: "passwordRequireUppercase",
    label: "Password Require Uppercase",
    type: "boolean",
    layout: "switch",
    required: false,
    double: true,
  },
  {
    name: "passwordRequireLowercase",
    label: "Password Require Lowercase",
    type: "boolean",
    layout: "switch",
    required: false,
    double: true,
  },
  {
    name: "passwordRequireNumber",
    label: "Password Require Number",
    type: "boolean",
    layout: "switch",
    required: false,
    double: true,
  },
  {
    name: "passwordRequireSpecialChar",
    label: "Password Require Special Character",
    type: "boolean",
    layout: "switch",
    required: false,
    double: true,
  },
  {
    name: "authSettingsLabel",
    label: t("Auth.Settings.Admin.Metadata.AuthSettingsLabel"),
    type: "label",
  },
  {
    name: "sessionTimeoutMinutes",
    label: "Session Timeout (minutes)",
    type: "number",
    required: true,
    double: true,
  },
  {
    name: "loginAttemptsLimit",
    label: "Login Attempts Limit",
    type: "number",
    required: true,
    double: true,
  },
  {
    name: "fileSettingsLabel",
    label: t("Auth.Settings.Admin.Metadata.FileSettingsLabel"),
    type: "label",
  },
  {
    name: "fileUploadMaxSizeMb",
    label: "File Upload Max Size (MB)",
    type: "number",
    required: true,
    double: true,
  },
  {
    name: "fileUploadMaxCount",
    label: "File Upload Max Count",
    type: "number",
    required: true,
    double: true,
  },
];
