import { useTranslation } from "react-i18next";

import tempLogo from "@/assets/images/brand/logo.png";
import { APP_VERSION } from "@/version";
import { useAppSelector } from "@/store/hooks";

const CopyRightView = ({ oneLine, short }: { oneLine?: boolean; short?: boolean }) => {
  const { t } = useTranslation();
  const { logo } = useAppSelector((state) => state.settings);

  const fixedText = {
    GeneratorShort: "Initia",
    Generator: "Initia",
    GeneratedBy: "Generated by",
    By: "by",
  };

  return (
    <div className={"px-1" + (oneLine ? " d-flex justify-content-between" : "")}>
      {oneLine ? (
        <small>{t("CopyRight.AppName")}</small>
      ) : (
        <a href="https://google.com" target="_blank" rel="noreferrer">
          <img src={logo || tempLogo} height="45" alt="Logo" />
        </a>
      )}

      {oneLine ? (
        ""
      ) : !short ? (
        <div className="mt-3">
          <small className="text-muted">
            {t("CopyRight.AllRightsReserved", {
              year: new Date().getFullYear(),
            })}{" "}
            <a
              href="https://www.BaseflowLabs.com/"
              target="_blank"
              rel="noreferrer"
              className="text-muted"
            >
              {t("CopyRight.BuilderShort")}
            </a>
          </small>
        </div>
      ) : (
        ""
      )}

      {oneLine ? (
        <a href="https://www.initia.com/" target="_blank" rel="noreferrer" className="text-muted">
          {fixedText.GeneratorShort}
        </a>
      ) : short ? (
        <div className="mt-3">
          <small className="text-muted">
            {fixedText.By}{" "}
            <a
              href="https://www.initia.com/"
              target="_blank"
              rel="noreferrer"
              className="text-muted"
            >
              {fixedText.GeneratorShort}
            </a>
          </small>
        </div>
      ) : (
        <div className="mt-3">
          <small className="text-muted">
            {fixedText.GeneratedBy}{" "}
            <a
              href="https://www.initia.com/"
              target="_blank"
              rel="noreferrer"
              className="text-muted"
            >
              {fixedText.Generator}
            </a>
          </small>
        </div>
      )}

      {oneLine && (
        <div>
          <small className="text-muted">V.{APP_VERSION}</small>
        </div>
      )}
    </div>
  );
};

export default CopyRightView;
