import { useTranslation } from "react-i18next";

import tempLogo from "@/assets/images/brand/logo.png";
import { APP_VERSION } from "@/version";
import { useAppSelector } from "@/store/hooks";

const CopyRightView = ({ oneLine }: { oneLine?: boolean }) => {
  const { t } = useTranslation();
  const { logo } = useAppSelector((state) => state.settings);

  const fixedText = {
    GeneratorShort: "Initia",
    Generator: "Initia",
    Owner: "Baseflow Labs",
    GeneratedBy: "Generated by",
    By: "by",
  };

  return (
    <div className={`px-1 ${oneLine ? "row" : ""}`}>
      <div className="col-4">
        {oneLine ? (
          <small>
            {fixedText.By} {fixedText.Owner}
          </small>
        ) : (
          <a href="https://initia.io" target="_blank" rel="noreferrer">
            <img src={logo || tempLogo} height="45" alt="Logo" />
          </a>
        )}
      </div>

      {oneLine ? (
        ""
      ) : (
        <div className="mt-3">
          <small className="text-muted">
            {t("CopyRight.AllRightsReserved", {
              year: new Date().getFullYear(),
            })}{" "}
            <a
              href="https://www.BaseflowLabs.com/"
              target="_blank"
              rel="noreferrer"
              className="text-muted"
            >
              {t("CopyRight.BuilderShort")}
            </a>
          </small>
        </div>
      )}

      <div className="col-4">
        {oneLine ? (
          <a href="https://www.initia.io/" target="_blank" rel="noreferrer" className="text-muted">
            {fixedText.GeneratorShort}
          </a>
        ) : (
          <div className="mt-3">
            <small className="text-muted">
              {fixedText.By}{" "}
              <a
                href="https://www.initia.io/"
                target="_blank"
                rel="noreferrer"
                className="text-muted"
              >
                {fixedText.GeneratorShort}
              </a>
            </small>
          </div>
        )}
      </div>

      <div className="col-4">
        {oneLine && (
          <div>
            <small className="text-muted">V.{APP_VERSION}</small>
          </div>
        )}
      </div>
    </div>
  );
};

export default CopyRightView;
